"""Component code generation for PolyBook.

Generates ready-to-use Qt/PySide code from component configurations.
"""

from typing import Dict, Any, List
import textwrap

from .registry import ComponentRegistry
from .export import Exporter


class CodeGenerator:
    """
    Generates complete Python code for Polygon UI components.
    """

    @staticmethod
    def generate_component_code(
        component_name: str,
        props: Dict[str, Any],
        stories: List[str] = None,
        theme_config: Dict[str, Any] = None,
        imports: List[str] = None
    ) -> str:
        """
        Generate full Python script for a component with props and theme.

        Args:
            component_name (str): Component name.
            props (Dict): Props to apply.
            stories (List, optional): Story variants.
            theme_config (Dict, optional): Theme settings.
            imports (List, optional): Additional imports.

        Returns:
            str: Complete Python code.
        """
        imports_list = imports or ["from polygon_ui import {component_name}"]
        if theme_config:
            imports_list.append("from polygon_ui.settings import PolygonProvider")

        code_parts = [
            "# Generated by PolyBook - Polygon UI Component Workshop",
            "# " + "="*60,
            "",
            "\n".join(imports_list),
        ]

        if theme_config:
            theme_str = textwrap.dedent(f"""
            # Theme Configuration
            provider = PolygonProvider()
            provider.theme.load_config({theme_config})
            """.strip())
            code_parts.append(theme_str)

        # Main component instantiation
        props_str = ", ".join([f"{k}={repr(v)}" for k, v in props.items()])
        main_code = f"""
        # Main Component
        component = {component_name}("Example {component_name}", {props_str})
        component.show()
        """
        code_parts.append(textwrap.dedent(main_code.strip()))

        if stories:
            for story in stories:
                story_code = f"""
                # Story: {story}
                story_component = {component_name}("Story: {story}", {props_str})
                # Add story-specific logic here
                """
                code_parts.append(textwrap.dedent(story_code.strip()))

        code_parts.append("\nif __name__ == '__main__':")
        code_parts.append("    import sys")
        code_parts.append("    from PySide6.QtWidgets import QApplication")
        code_parts.append("    app = QApplication(sys.argv)")
        code_parts.append("    sys.exit(app.exec())")

        return "\n\n".join(code_parts)

    @classmethod
    def generate_from_registry(cls, registry: ComponentRegistry, selected_components: List[str]) -> Dict[str, str]:
        """
        Generate code for multiple components from registry.
        """
        codes = {}
        for name in selected_components:
            if name in registry:
                comp_data = registry[name]
                codes[name] = cls.generate_component_code(
                    name, comp_data.get("default_props", {}),
                    comp_data.get("stories", []),
                    theme_config=None
                )
        return codes